package com.demos.event_planner;

import java.lang.Number;

rule "remove-song-gaps"
	dialect "mvel"
	when
		$firstSong : SongEvent( $firstName : name, $firstStartTime : startTime, $firstDuration : duration)
		not (SongEvent( this metby [10s] $firstSong )) 
		$secondSong : SongEvent( $secondStartTime : startTime after $firstStartTime )
		not (SongEvent( startTime after $firstStartTime , startTime before $secondStartTime )) 
	then
		System.out.println($firstName + " has too much silence after it, moving " + $secondSong.getName() + " up")
		$secondSong.setStartTime( new java.util.Date($firstStartTime.getTime() + $firstDuration + 5000) );
		update($secondSong);
end
