package com.eventplanning.dataobjects;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BarRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String drinkName;
	private java.lang.Long totalAlcohol;
	private java.util.Date requestTime;
	private java.lang.String guestName;

	private java.lang.String status;

	public BarRequest() {
	}

	public java.lang.String getDrinkName() {
		return this.drinkName;
	}

	public void setDrinkName(java.lang.String drinkName) {
		this.drinkName = drinkName;
	}

	public java.lang.Long getTotalAlcohol() {
		return this.totalAlcohol;
	}

	public void setTotalAlcohol(java.lang.Long totalAlcohol) {
		this.totalAlcohol = totalAlcohol;
	}

	public java.util.Date getRequestTime() {
		return this.requestTime;
	}

	public void setRequestTime(java.util.Date requestTime) {
		this.requestTime = requestTime;
	}

	public java.lang.String getGuestName() {
		return this.guestName;
	}

	public void setGuestName(java.lang.String guestName) {
		this.guestName = guestName;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public BarRequest(java.lang.String drinkName, java.lang.Long totalAlcohol,
			java.util.Date requestTime, java.lang.String guestName,
			java.lang.String status) {
		this.drinkName = drinkName;
		this.totalAlcohol = totalAlcohol;
		this.requestTime = requestTime;
		this.guestName = guestName;
		this.status = status;
	}

}