package com.eventplanning.dataobjects;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Event implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int tableSize;

	public Event() {
	}

	public int getTableSize() {
		return this.tableSize;
	}

	public void setTableSize(int tableSize) {
		this.tableSize = tableSize;
	}

	public Event(int tableSize) {
		this.tableSize = tableSize;
	}

}