package com.eventplanning.dataobjects;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class GoodieBag implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String guestName;
	private java.util.List<java.lang.String> items;

	public GoodieBag() {
	}

	public java.lang.String getGuestName() {
		return this.guestName;
	}

	public void setGuestName(java.lang.String guestName) {
		this.guestName = guestName;
	}

	public java.util.List<java.lang.String> getItems() {
		if (null == this.items) {
			this.items = new java.util.ArrayList<>();
		}
		return this.items;
	}

	public void setItems(java.util.List<java.lang.String> items) {
		this.items = items;
	}

	public GoodieBag(java.lang.String guestName,
			java.util.List<java.lang.String> items) {
		this.guestName = guestName;
		this.items = items;
	}

}