package com.eventplanning.dataobjects;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Table implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.util.List<com.eventplanning.dataobjects.Guest> guests;

	public Table() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.util.List<com.eventplanning.dataobjects.Guest> getGuests() {
		if (null == this.guests) {
			this.guests = new java.util.ArrayList<>();
		}
		return this.guests;
	}

	public void setGuests(java.util.List<com.eventplanning.dataobjects.Guest> guests) {
		this.guests = guests;
	}

	public void addGuests(java.util.List<com.eventplanning.dataobjects.Guest> guests) {
		getGuests().addAll(guests);
	}

	public Table(java.lang.String name,
			java.util.List<com.eventplanning.dataobjects.Guest> guests) {
		this.name = name;
		this.guests = guests;
	}

}