package com.demos.event_planner;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Event implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int tableSize;

	private java.lang.String partyBeingSeated;

	public Event() {
	}

	public int getTableSize() {
		return this.tableSize;
	}

	public void setTableSize(int tableSize) {
		this.tableSize = tableSize;
	}

	public java.lang.String getPartyBeingSeated() {
		return this.partyBeingSeated;
	}

	public void setPartyBeingSeated(java.lang.String partyBeingSeated) {
		this.partyBeingSeated = partyBeingSeated;
	}

	public Event(int tableSize, java.lang.String partyBeingSeated) {
		this.tableSize = tableSize;
		this.partyBeingSeated = partyBeingSeated;
	}

}