package com.demos.event_planner;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Guest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.lang.String party;
	private int age;

	private java.lang.String entree;

	private java.lang.String dessert;

	private java.lang.Boolean peanutAllergy;

	private java.util.List<java.lang.String> doorPrize;

	private java.lang.String meatPreference;

	public Guest() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getParty() {
		return this.party;
	}

	public void setParty(java.lang.String party) {
		this.party = party;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public java.lang.String getEntree() {
		return this.entree;
	}

	public void setEntree(java.lang.String entree) {
		this.entree = entree;
	}

	public java.lang.String getDessert() {
		return this.dessert;
	}

	public void setDessert(java.lang.String dessert) {
		this.dessert = dessert;
	}

	public java.lang.Boolean getPeanutAllergy() {
		return this.peanutAllergy;
	}

	public void setPeanutAllergy(java.lang.Boolean peanutAllergy) {
		this.peanutAllergy = peanutAllergy;
	}

	public java.util.List<java.lang.String> getDoorPrize() {
		if (null == this.doorPrize) {
			this.doorPrize = new java.util.ArrayList<>();
		}
		return this.doorPrize;
	}

	public void setDoorPrize(java.util.List<java.lang.String> doorPrize) {
		this.doorPrize = doorPrize;
	}

	public void addDoorPrizeItem(java.lang.String item) {
		getDoorPrize().add(item);
	}

	public java.lang.String getMeatPreference() {
		return this.meatPreference;
	}

	public void setMeatPreference(java.lang.String meatPreference) {
		this.meatPreference = meatPreference;
	}

	public Guest(java.lang.String name, java.lang.String party, int age,
			java.lang.String entree, java.lang.String dessert,
			java.lang.Boolean peanutAllergy,
			java.util.List<java.lang.String> doorPrize,
			java.lang.String meatPreference) {
		this.name = name;
		this.party = party;
		this.age = age;
		this.entree = entree;
		this.dessert = dessert;
		this.peanutAllergy = peanutAllergy;
		this.doorPrize = doorPrize;
		this.meatPreference = meatPreference;
	}

}