package com.demos.event_planner;

import java.time.OffsetDateTime;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class SongEvent implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.util.Date startTime;

	private java.lang.Long duration;

	public SongEvent() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.util.Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(java.util.Date startTime) {
		this.startTime = startTime;
	}

	public java.lang.Long getDuration() {
		return this.duration;
	}

	public void setDuration(java.lang.Long duration) {
		this.duration = duration;
	}

	public SongEvent(java.lang.String name, java.util.Date startTime,
			java.lang.Long duration) {
		this.name = name;
		this.startTime = startTime;
		this.duration = duration;
	}

}