package com.eventplanning.dining;

import com.eventplanning.dataobjects.Event;
import com.eventplanning.dataobjects.Guest;
import com.eventplanning.dataobjects.Table;

rule "move-guest-to-table"
	dialect "mvel"
	ruleflow-group "seat-guests"
	when
		Event( $tableSize : tableSize != null )
		$guest : Guest( $partyName : party != null , entree != null )
		$table : Table( name == $partyName , guests.size() < $tableSize)
	then
		$table.getGuests().add($guest);
		retract($guest);
		update($table);
end